### ISSUE TITLE
error docker

### ISSUE THREAD

**Issue by jerryhager** [charlie-captain/MeowAI#3]
Hi,

I am trying to run your docker image but receive this error after seconds:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from src.api import server
  File "/app/src/api/server.py", line 7, in <module>
    from src.api import api
  File "/app/src/api/api.py", line 7, in <module>
    from src.api import error_codes
  File "/app/src/api/error_codes.py", line 72, in <module>
    auth_error_codes: dict[int, str] = {
TypeError: 'type' object is not subscriptable

Is there a solution?

regards,

jHod

**Comment by charlie-captain** [comment]
[#8a98373](https://github.com/charlie-captain/MeowAI/commit/8a983734b7b9531ffd7c8658acae5e3c009bc409) fixed.
